services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: test
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  redis:
    image: redis:7
    container_name: redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: ["redis-server", "--appendonly", "yes"]

  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: gnid70136/gnid31:latest
    container_name: backend
    restart: always
    ports:
      - "8081:8080"
    depends_on:
      - mysql
      - redis
    environment:
      DATABASE_URL: mysql://root:123456@mysql:3306/test
      REDIS_PORT: 6379
      REDIS_HOST: redis

volumes:
  mysql_data:
  redis_data:
