name: Build & Deploy Docker App

on:
  push:
    branches:
      - main

env:
  DOCKER_IMAGE: gnid70136/gnid31

jobs:
  build_and_push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_TOKEN }}

    - name: Build Docker image
      run: |
        docker build -t $DOCKER_IMAGE:latest .

    - name: Push Docker image
      run: |
        docker push $DOCKER_IMAGE:latest

  deploy:
    needs: build_and_push
    runs-on: ubuntu-latest

    steps:
    - name: Deploy to EC2
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: ${{ secrets.EC2_HOST_1 }}
        username: ubuntu
        key: ${{ secrets.EC2_SSH_KEY }}
        script: |
          docker compose pull
          docker compose up -d --no-deps --force-recreate app


